### ISSUE TITLE
Network property should cause a recursion error

### ISSUE THREAD

**Issue by ross-spencer** [Python-Cardano/pycardano#282]
**Describe the bug**

In the Ogmios context the network property returns self.nework. This shouldn't be possible, and when calling users are likely to see:

```text
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ross-spencer/git/orcfax/cnt/src/cnt/main.py", line 227, in <module>
    main()
  File "/home/ross-spencer/git/orcfax/cnt/src/cnt/main.py", line 223, in main
    cnt_collect()
  File "/home/ross-spencer/git/orcfax/cnt/src/cnt/main.py", line 188, in cnt_collect
    print("network:", context.network)
  File "/home/ross-spencer/git/orcfax/cnt/venv/lib/python3.10/site-packages/pycardano/backend/ogmios.py", line 247, in network
    return self.network
  File "/home/ross-spencer/git/orcfax/cnt/venv/lib/python3.10/site-packages/pycardano/backend/ogmios.py", line 247, in network
    return self.network
  File "/home/ross-spencer/git/orcfax/cnt/venv/lib/python3.10/site-packages/pycardano/backend/ogmios.py", line 247, in network
    return self.network
  [Previous line repeated 991 more times]
RecursionError: maximum recursion depth exceeded
```

Ref: 

https://github.com/Python-Cardano/pycardano/blob/9b5d367fddd6d370b508d2953dc67cf3deac4990/pycardano/backend/ogmios.py#L244-L247

Snippet: 

```python
    @property
    def network(self) -> Network:
        """Get current network"""
        return self.network
```

**To Reproduce**
Steps to reproduce the behavior. e.g. A python script.

Create an Ogmios Pycardano conext:

```
    context: OgmiosChainContext = OgmiosChainContext(
        ws_url=OGMIOS_URL, network=Network.MAINNET
    )
```

And try and return its network propery:

```
    print("network:", context.network)
```

**Logs**
If applicable, add logs to help explain your problem.

Error trace as per above.

**Expected behavior**

When calling the network property it returns the network that the context is associated with and doesn't cause a recursion error. 

**Environment and software version (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04.3 LTS, Mac OS 12.1]
 - PyCardano Version [e.g. 0.1.1]

```
pycardano==0.10.0
```

Python 3.10.12.

**Additional context**

N/A.

**Comment by cffls** [comment]
Thanks for reporting this issue! It is fixed in https://github.com/Python-Cardano/pycardano/commit/fdff5f2c6374a02a76349bc5800de12a106e78fd.
