### ISSUE TITLE
Guidance creating address from keys saved as JSON

### ISSUE THREAD

**Issue by 34r7h** [Python-Cardano/pycardano#44]
Hey guys. I'm having trouble getting an address. I've tried variations but haven't  got it right yet. Please look and lmk what I'm doing wrong.

Here's my code, currently trying the from_cbor method:
```
jsonsecret = json.loads(secret)
pkey  = jsonsecret['payment']['verification']['cborHex']
skey  = jsonsecret['stake']['verification']['cborHex']

print(pkey, skey)

base_address = Address(payment_part=PaymentVerificationKey.from_cbor(pkey), staking_part=StakeVerificationKey.from_cbor(skey), network=Network.MAINNET)
```

Here's my JSON string example:
```
secret = '{"payment":{"signing":{"type":"PaymentSigningKeyShelley_ed25519","description":"PaymentSigningKeyShelley_ed25519","cborHex":"5820b56b0401431a24f97fab426148c5c55b9df2c3aa69f24e5c50465fc8ae0bdf30"},"verification":{"type":"PaymentVerificationKeyShelley_ed25519","description":"PaymentVerificationKeyShelley_ed25519","cborHex":"582091f7710e0d57878b94b18f8d3bb9c2d884e055ca6797607e020eb7d6af222648"}},"stake":{"signing":{"type":"StakeSigningKeyShelley_ed25519","description":"StakeSigningKeyShelley_ed25519","cborHex":"5820c0337fcfb1504f14fa83352fa2a1a86d71bc74789b687baa03bd386d23255c18"},"verification":{"type":"StakeVerificationKeyShelley_ed25519","description":"StakeVerificationKeyShelley_ed25519","cborHex":"5820427693e248678fd3b58dc9c08ba4afa2876477bf79d3720bdc604be12d2bed5e"}}}'
```
Error message:
```
err: PythonShellError: pycardano.exception.InvalidAddressInputException: Cannot construct a shelley address from a combination of payment part: {"type": "PaymentVerificationKeyShelley_ed25519", "description": "PaymentVerificationKeyShelley_ed25519", "cborHex": "582091f7710e0d57878b94b18f8d3bb9c2d884e055ca6797607e020eb7d6af222648"} and stake part: {"type": "StakeVerificationKeyShelley_ed25519", "description": "StakeVerificationKeyShelley_ed25519", "cborHex": "5820427693e248678fd3b58dc9c08ba4afa2876477bf79d3720bdc604be12d2bed5e"}
      at PythonShell.parseError (/Users/34r7h/a/cardano-python-js/node_modules/python-shell/index.js:295:21)
      at terminateIfNeeded (/Users/34r7h/a/cardano-python-js/node_modules/python-shell/index.js:190:32)
      at ChildProcess.<anonymous> (/Users/34r7h/a/cardano-python-js/node_modules/python-shell/index.js:182:13)
      at ChildProcess.emit (events.js:314:20)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
      ----- Python Traceback -----
      File "/Users/34r7h/a/cardano-python-js/python/getaddress.py", line 26, in <module>
        base_address = Address(payment_part=PaymentVerificationKey.from_cbor((pkey)), staking_part=StakeVerificationKey.from_cbor(skey), network=Network.MAINNET)
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pycardano/address.py", line 201, in __init__
        self._address_type = self._infer_address_type()
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pycardano/address.py", line 233, in _infer_address_type
```

**Comment by cffls** [comment]
Hi @34r7h , you will need to pass the hash of verification key to Address constructor:

```python
base_address = Address(payment_part=PaymentVerificationKey.from_cbor(pkey).hash(), staking_part=StakeVerificationKey.from_cbor(skey).hash(), network=Network.MAINNET)
```

**Comment by 34r7h** [comment]
Thanks Jerry!
